version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FDC_API_KEY: ${FDC_API_KEY}
      SPOONACULAR_API_KEY: ${SPOONACULAR_API_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000

volumes:
  db_data:
