name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Change to client directory
        run: cd client
      - name: Build the client Docker image
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: docker build -f Dockerfile -t labdash/dockerize-vuejs-app-client .
      - name: Change to server directory
        run: cd ../server
      - name: Build the server Docker image
        run: docker build -f Dockerfile -t labdash/dockerize-vuejs-app-server .
